### ISSUE TITLE
ValorantStreamOverlay.exe not launching

### ISSUE THREAD

**Issue by RadixR** [RumbleMike/ValorantStreamOverlay#1]
so I followed all the steps in the tutorial and downloaded the necessary .NET core framework, 
![image](https://user-images.githubusercontent.com/36137984/103146831-e0bbea00-471c-11eb-96b2-aba65bb05f6d.png)
but I'm still greeted with this message, I tried downloading the older version as stated (3.1.0) 
Am I missing something? 

Thanks in advance!

**Comment by mmattbtw** [comment]
try downloading x86 .NET core

**Comment by kesavvvvv** [comment]
try these

(IF IT DOESNT OPEN!!!!, Download this from Microsoft:)
[x86]: https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.10-windows-x86-installer
^^^^^^^^^^^ THIS ONE FIRST BTW ^^^^^^^^^^^^^
[x64]: https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.10-windows-x64-installer
