### ISSUE TITLE
Microsoft .NET

### ISSUE THREAD

**Issue by dgw1016** [RumbleMike/ValorantStreamOverlay#104]
"Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Unable to find the specified file."

After clicking continue to clear this message, the stream overlay itself only says "INVALID" and there's a question mark in place of my rank rather than my true rank. All the number slots are filled with 0s.

**Comment by ornobaadi** [comment]
https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.10-windows-x86-installer

Try installing this
