### ISSUE TITLE
UNRATED I 0 RP I -300 elo

### ISSUE THREAD

**Issue by haristajik** [RumbleMike/ValorantStreamOverlay#106]
It shows UNRATED , 0 RP , -300 elo although I have a silver 2 rank and I play comp. Do I have to run the software while I play comp?
I play on middle eastern servers and the pictures are attached as follows : 
https://drive.google.com/drive/folders/1qFUuFeDtXaB4Ol4qWHx06IHdoLM4zRiD?usp=sharing
**I have not run the software while playing comp please tell me if this is the issue**

**Comment by DiabolusGX** [comment]
if you haven't played ranked on the account in your last 20 games you'll have this issue. everything is covered in [issue #17](https://github.com/RumbleMike/ValorantStreamOverlay/issues/17)

**Comment by haristajik** [comment]
> if you haven't played ranked on the account in your last 20 games you'll have this issue. everything is covered in [issue #17](https://github.com/RumbleMike/ValorantStreamOverlay/issues/17)

I have attached the photos of me playing ranked . Despite this I have this issue .

**Comment by mohnishkarri** [comment]
Your account looks like a boosted one as you have ranked up from silver 1 to silver 2 in one match. Do a thing change the server and try again. Like I see you are Asia pacific so change to LATM and reload the app and then change the server to Asia pacific again and reload. If this won't solve the problem you need to find a solution on your own.

**Comment by HolidayLNX** [comment]
> It shows UNRATED , 0 RP , -300 elo although I have a silver 2 rank and I play comp. Do I have to run the software while I play comp?
> I play on middle eastern servers and the pictures are attached as follows :
> https://drive.google.com/drive/folders/1qFUuFeDtXaB4Ol4qWHx06IHdoLM4zRiD?usp=sharing
> **I have not run the software while playing comp please tell me if this is the issue**

Does your password contains special characters? If yes change it to a simple password.. it works.. This issue will be fixed in the upcoming versions probably.

**Comment by ElvioG** [comment]
Better wait for the next update instead change a strong password 👍

**Comment by haristajik** [comment]
I have updated the software and I have tried all the ways mentioned above except changing my password .Still it does not work 😶.

**Comment by ElvioG** [comment]
> I have updated the software and I have tried all the ways mentioned above except changing my password .Still it does not work 😶.

Same

**Comment by Koupah** [comment]
In regards to the original issue, see this reply to this other issue: https://github.com/RumbleMike/ValorantStreamOverlay/issues/126#issuecomment-756086234

**Comment by RumbleMike** [comment]
Update regarding special characters has been pushed: https://github.com/RumbleMike/ValorantStreamOverlay/releases/tag/1.1.0.5
