### ISSUE TITLE
Error RP and ELO

### ISSUE THREAD

**Issue by Dariusgd19** [RumbleMike/ValorantStreamOverlay#107]
It does not raise RP or ELO, they stay at 99 even if you lose or win games.
I am iron 1. If someone knows something please say so, it is very frustrating not being able to see it

**Comment by mohnishkarri** [comment]
You are hard struck in iron 1 friend. Please refer thi #17 . And you need to grind hard to get out of iron 1 . Even i am in the same problem. The only advice here is try to win a lot of games to decrease the negative elo of the account . after you gain some positive elo it will start displaying or else open a new account.

**Comment by HolidayLNX** [comment]
> It does not raise RP or ELO, they stay at 99 even if you lose or win games.
> I am iron 1. If someone knows something please say so, it is very frustrating not being able to see it

Had the same problem for a friend. When you get to  Iron 2 it starts working. Not sure why Iron 1 has this problem.. but try hard to get to Iron 2 and you will be able to see your elo properly.
