### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Joaking275** [RumbleMike/ValorantStreamOverlay#11]
I already installed the .NET Core program but it tells me that I have to reinstall it yet, what do I have to do?

**Comment by OsirisFrik** [comment]
same case

**Comment by OsirisFrik** [comment]
@Joaking275 I have a same case, but I fixed it installing x86 .NET Core, not x64 version

**Comment by JamaHCS** [comment]
Same, i will try @OsirisFrik solution...

**Comment by RumbleMike** [comment]
It has to be x86, some people have uninstalled x64, and then it has functioned, but the issue with .NET core isn't something I can fix on my own.

**Comment by jpmasud** [comment]
Can confirm, just installing x86 worked (no need to uninstall x64)
