### ISSUE TITLE
question: last three games display

### ISSUE THREAD

**Issue by McFLoDuR** [RumbleMike/ValorantStreamOverlay#111]
The competitive games from what time frame are displayed?
Is it limited to one week?

**Comment by Superamaja** [comment]
Pretty sure it gets the info from your career so it can be there from the start of the act until the next act.

**Comment by Exakayem** [comment]
The application pulls the data of the last 20 matches, the response contains unrated as well as rated matches. The oldest match I get as a response on my account (with an application I built) is from May 2nd, 2020 (an unrated one).
