### ISSUE TITLE
Login is incorrect, please fix log in settings

### ISSUE THREAD

**Issue by nroomy** [RumbleMike/ValorantStreamOverlay#112]
Game updated a few mins ago, a few dependencies were installed, and ever since then the app seems broken! Any updates?

**Comment by ashwinsrini** [comment]
Same here, maybe the app requires an update since the game just got a new patch. Don't think theres any workaround we can do for this, we'll have to wait for @RumbleMike to update the app.

**Comment by adamCSzombie** [comment]
probably riot updated their API mostlikely

**Comment by HolidayLNX** [comment]
Same issue for meeee :(

**Comment by TrippyTwitty** [comment]
hi,i have same issues too...pls love ur overlay on my stream...i hope you fix that asap

**Comment by Inflixct** [comment]
Yea me and my friends have the same issue

**Comment by AkivaKugler** [comment]
nope he just posted that it doesnt work anymore!
![Screenshot 2021-01-06 152747](https://user-images.githubusercontent.com/77076727/103816993-e0ccbb80-5033-11eb-8f54-f37b373d8047.jpg)

**Comment by MadMax987** [comment]
same, and I just ranked up and I'm afraid to play another ranked, because I don't know how much elo I have

**Comment by Lafa02** [comment]
For @RumbleMike i have developed a website that do what your program do, so i think it's fair to help you where you helped me, i simply change the 'redirect_uri' in the first api call the 'https://auth.riotgames.com/api/v1/authorization' with this value: 'https://playvalorant.com/' and everything should works again!

**Comment by MadMax987** [comment]
> nope he just posted that it doesnt work anymore!
> ![Screenshot 2021-01-06 152747](https://user-images.githubusercontent.com/77076727/103816993-e0ccbb80-5033-11eb-8f54-f37b373d8047.jpg)

did he posted this? I think it was already there before I downloaded the overlay like a week ago

**Comment by MadMax987** [comment]
> For @RumbleMike i have developed a website that do what your program do, so i think it's fair to help you where you helped me, i simply changed the 'redirect_uri' in the first api call the 'https://auth.riotgames.com/api/v1/authorization' with this value: 'https://playvalorant.com/' and everything should works again!

can you explain it more please??? I would really appreciate it

**Comment by CASyHD** [comment]
> For @RumbleMike i have developed a website that do what your program do, so i think it's fair to help you where you helped me, i simply changed the 'redirect_uri' in the first api call the 'https://auth.riotgames.com/api/v1/authorization' with this value: 'https://playvalorant.com/' and everything should works again!

does your website require you login data, or can you do it with official riot login?

**Comment by shakeabi** [comment]
I made a website as well, and as of now no, it does require login data.

**Comment by shakeabi** [comment]
> > For @RumbleMike i have developed a website that do what your program do, so i think it's fair to help you where you helped me, i simply changed the 'redirect_uri' in the first api call the 'https://auth.riotgames.com/api/v1/authorization' with this value: 'https://playvalorant.com/' and everything should works again!
> 
> can you explain it more please??? I would really appreciate it

So basically  as the first step of login this particular URL is required, however it doesn't work anymore and the new URL works. Regarding "can you fix it urself", yes if you can build the exe by yourself, else wait for RumbleMike to release an update.

**Comment by Exakayem** [comment]
> > For @RumbleMike i have developed a website that do what your program do, so i think it's fair to help you where you helped me, i simply changed the 'redirect_uri' in the first api call the 'https://auth.riotgames.com/api/v1/authorization' with this value: 'https://playvalorant.com/' and everything should works again!
> 
> can you explain it more please??? I would really appreciate it

There is nothing more to explain, the first authentication call has a "redirect_uri" parameter in it that can be changed to the one they mentioned. It's nothing you as a user can do within the program, it has to be adapted by the developer. If you are making the API calls yourself, you can just change the parameter to the value mentioned.

**Comment by Lafa02** [comment]
> > For @RumbleMike i have developed a website that do what your program do, so i think it's fair to help you where you helped me, i simply changed the 'redirect_uri' in the first api call the 'https://auth.riotgames.com/api/v1/authorization' with this value: 'https://playvalorant.com/' and everything should works again!
> 
> can you explain it more please??? I would really appreciate it

Apparently doesn't redirect to https://beta.playvalorant.com/opt_in anymore, so i basicly change the old url (https://beta.playvalorant.com/opt_in) with the new one and it works, but since this is a compiled program only rumblemike is able to change it

**Comment by andrecadete** [comment]
If @Lafa02 is correct this PR should contain a working version. As stated I don't have time to build and test it it right now so if anyone else does, please go ahead! 

Cheers
