### ISSUE TITLE
Login is incorrect

### ISSUE THREAD

**Issue by Kliffff** [RumbleMike/ValorantStreamOverlay#114]
Login is incorrect, please fix login in settings "but my user name and password is correct"

![image](https://user-images.githubusercontent.com/77077117/103818136-e1506b00-50a2-11eb-9100-2b64a62d5983.png)

**Comment by MadMax987** [comment]
Dude same issue is in the below one

**Comment by MohamedFandies** [comment]
Same here

**Comment by apubtw** [comment]
same here man:c

**Comment by CASyHD** [comment]
https://twitter.com/RumbleMikee/status/1346909408551260160
Riot Login is broken, not the app or api I think

**Comment by d3iBiD12** [comment]
same :(
