### ISSUE TITLE
Login Incorrect but all the information is correct?

### ISSUE THREAD

**Issue by CarThax08** [RumbleMike/ValorantStreamOverlay#117]
So, when I go to launch the program, after setting my Username and Password, it says the information is incorrect. I changed my password and I literally copy and pasted my password from the Riot Games Change Password screen into the application and it still did that. I think something may be wrong but I'm not certain...

**Comment by FeedrNoa** [comment]
have this same issue tried reinstall and still doesnt work

**Comment by CarThax08** [comment]
Same here

**Comment by pruthvirathod** [comment]
Patched by Riot.

**Comment by DemonsChild** [comment]
same here, solution would be cool if anyone figures it out

**Comment by CarThax08** [comment]
Damn, that sucks.

**Comment by CarThax08** [comment]
A FIX HAS BEEN RELEASED.

**Comment by DemonsChild** [comment]
where @CarThax08

**Comment by Exakayem** [comment]
> where @CarThax08

https://github.com/RumbleMike/ValorantStreamOverlay/releases/tag/1.1.0.5
