### ISSUE TITLE
Login is incorrect?

### ISSUE THREAD

**Issue by ARoman02** [RumbleMike/ValorantStreamOverlay#118]
It says the login is incorrect but I'm positive the credentials are correct.
Server is NA, and I've tried to change the refresh time as well.

**Comment by CarThax08** [comment]
An update just released that fixed it for me. Try updating.

**Comment by ARoman02** [comment]
Updated. The error went away but it still says unranked -300 elo :(

**Comment by RumbleMike** [comment]
Play a ranked game to show games again.
