### ISSUE TITLE
Can't seem to login

### ISSUE THREAD

**Issue by CEQrator** [RumbleMike/ValorantStreamOverlay#119]
Login doesn't work for me. I have tried changing my password to exclude characters that may not be supported, such as £¤$@{´\ etc., to no avail. 
![image](https://user-images.githubusercontent.com/77079413/103824107-90754e00-5073-11eb-9f82-8079cbbca524.png)

**Comment by picklejason** [comment]
Fixed in #115 . It should work after updating to the newest version.
