### ISSUE TITLE
Bug ? 

### ISSUE THREAD

**Issue by Alnerius** [RumbleMike/ValorantStreamOverlay#12]
Cuando maximizo la pantalla se deforma, tendrías que quitar lo de poder maximizar la pantalla.
When I maximize the screen is deformed, you would have to remove the be able to maximize the screen.

![pantalla f](https://user-images.githubusercontent.com/69075790/103258002-22d16f80-4959-11eb-87bd-0677801733fc.PNG)

**Comment by BobbyESP** [comment]
Hola, Alenerius. Tienes que actualizar a la última versión (0.9.9). En esta, la ventana ya no se puede redimensionar. Gracias. Pronto se añadirá el Auto Actualizar. Gracias.
