### ISSUE TITLE
Prevents Valorant Login

### ISSUE THREAD

**Issue by Jxd3n** [RumbleMike/ValorantStreamOverlay#123]
I just started using Valorant Stream Overlay for ELO Tracking. After I installed the tracker, I attempted to launch Valorant, but it prompted me with the login screen, but it wasn't valorant, just a generic Riot Games login app. Of course, I entered my info, it didn't work, it had a problem with something about checking my internet and things like that. I did. It was working, so then I checked the riot games site and attempted to log in. IT WORKED. It was only after I reset my computer that I could log-in.

**Comment by RumbleMike** [comment]
Not sure, had to have been a pc issue because this program does not touch your riot installation.
