### ISSUE TITLE
-elo and doesnt show any stats

### ISSUE THREAD

**Issue by myaccountiscursed** [RumbleMike/ValorantStreamOverlay#124]
I tried logging in to it and was excited to see my elo but then it just shows -300 elo no rank no rp and nothing, however i tried using my alt account and everything shows I also asked my friend to log in to my account using his stream overlay and his was working fine but when he logged in to my account it also showed the same thing and I dk what to do
![val overlay](https://user-images.githubusercontent.com/77091001/103855586-f7cfe400-50ed-11eb-9213-91302b4440a3.PNG)

**Comment by raj-bb** [comment]
@myaccountiscursed Please check if your profile is public on your riot account settings.

**Comment by myaccountiscursed** [comment]
> @myaccountiscursed Please check if your profile is public on your riot account settings.

where is , went there saw nothing

**Comment by myaccountiscursed** [comment]
nvm im so sorry but I played a ranked game and my stats are showing now mbmb

**Comment by Koupah** [comment]
You can see the reasoning for this here: https://github.com/RumbleMike/ValorantStreamOverlay/issues/126#issuecomment-756086234

Solution: Play a ranked game & have a rank
