### ISSUE TITLE
WTF xD

### ISSUE THREAD

**Issue by HolidayLNX** [RumbleMike/ValorantStreamOverlay#125]
I got +73 for a Defeat.. Whereas it showed "Rating decreased" icon ingame! Can somebody explain?? Is this the program's glitch or is riot ranking system totally fucked up? :S
![s](https://user-images.githubusercontent.com/76883571/103860439-9e61b800-50e1-11eb-962d-5e9f77733184.PNG)

**Comment by Exakayem** [comment]
I've already noticed a similar difference between the arrows and the rating change (though it wasn't that crazy). It's definitely not a bug of the application.

**Comment by Koupah** [comment]
The rating decreased, increased and stayed the same symbols don't necessarily represent what your elo is doing. This happens particularly when smurfing (because you lost but played better than they expected). 

Think nothing of it and be happy you're almost Silver 1, congratulations!

**Comment by squee7** [comment]
i had the same situation. I played really bad but we won the match .. +79 elo points and Silver1

**Comment by HolidayLNX** [comment]
LOL.. So i won the next game and got my Silver guys xD. Its weird.. the ranking system but i am happy for the silver haha :D
