### ISSUE TITLE
No elo 

### ISSUE THREAD

**Issue by TicianoBLTO** [RumbleMike/ValorantStreamOverlay#13]
i have installed the proggram and config the files and all work but the statistics are incorrect i am gold 1 and this say me ¨Unranked¨ and -300 elo

**Comment by BobbyESP** [comment]
First, make sure u selected the correct region. 2nd, make sure what your JSON file is like this.
![imagen_2020-12-29_101054](https://user-images.githubusercontent.com/60316747/103272835-221ef480-49be-11eb-818e-343f9e9f8c13.png)

**Comment by RumbleMike** [comment]
You need to set your region properly.

**Comment by skittles9823** [comment]
@RumbleMike 
> You need to set your region properly.

Could this not also be caused by not having any recent ranked games?

**Comment by RumbleMike** [comment]
> @RumbleMike
> 
> > You need to set your region properly.
> 
> Could this not also be caused by not having any recent ranked games?

Yes this could aswell.
