### ISSUE TITLE
Launch issue

### ISSUE THREAD

**Issue by eyrealex** [RumbleMike/ValorantStreamOverlay#138]
When launching the application now it deletes itself, have re downloaded from git hub multiple times and app keeps deleting,

**Comment by johnalbert-dot-py** [comment]
did you try to download the latest release?

**Comment by johnalbert-dot-py** [comment]
and also please turn off antivirus `cause sometimes it detect as a 'virus'

**Comment by eyrealex** [comment]
Yup, off the pc for the night. Will try again tomorrow to see if a restart was all that was required.

**Comment by eyrealex** [comment]
Fixed with a pc restart.
