### ISSUE TITLE
Login not correct

### ISSUE THREAD

**Issue by qureuyt** [RumbleMike/ValorantStreamOverlay#147]
I have restarted my pc and everything, re downloaded the app and tried login in i know my info is correct it keeps saying incorrect and not showing me a rank just unranked even though i am ranked.

**Comment by Sandy-Garrido** [comment]
Are you certain you've  set the correct Region?

**Comment by qureuyt** [comment]
> Are you certain you've set the correct Region?

yes im na and its set to na just says invalid login and then shows im unranked even when i reinstall everything and make sure everything is correct.

**Comment by ManuParmarXd** [comment]
same

**Comment by wannabe993** [comment]
is says North America | LATAM

**Comment by RumbleMike** [comment]
When you are logging in, the region set does not matter. If you do not get an error message saying your login was incorrect then it is a region issue. 

If you haven't updated to the mandatory new version: https://github.com/RumbleMike/ValorantStreamOverlay/releases/tag/1.1.0.5

Please do so.
