### ISSUE TITLE
How to get competitive rank of the player using Valorant Client Api

### ISSUE THREAD

**Issue by alfe06** [RumbleMike/ValorantStreamOverlay#148]
Is there any possibilities to get competitive rank of the player by using Valorant Client Api as you did for "TierAfterUpdate"?

**Comment by alfe06** [comment]
or is there any other ways that I can get competitive rank of the player?

**Comment by RumbleMike** [comment]
Not the place to ask, please go to my discord or reference my documentation on the Valorant Client API
