### ISSUE TITLE
CANT LOGIN

### ISSUE THREAD

**Issue by shinjimazad** [RumbleMike/ValorantStreamOverlay#151]
"Login is incorrect, please fix login in settings"

tho ik my username and password is correct this still pops up everytime

i even changed my password but nothing changes. help!

**Comment by DemonSlayerPro** [comment]
you need to download the latest version

**Comment by H0tZ3ra** [comment]
Yeah, download the update, it is fixed in a new version.

**Comment by RumbleMike** [comment]
https://github.com/RumbleMike/ValorantStreamOverlay/releases/tag/1.1.0.5
