### ISSUE TITLE
there is something wrong

### ISSUE THREAD

**Issue by DemonSlayerPro** [RumbleMike/ValorantStreamOverlay#152]
I don't think it's possible, how is this possible?
![image](https://user-images.githubusercontent.com/31426262/104088835-f5929480-5269-11eb-948f-06f032a7137c.png)
i tried restarting the overlay a couple of times...

**Comment by H0tZ3ra** [comment]
uuuh, idk, I see that you have 15 kills and 15 deaths, so maybe like you have 1 k\d, and it is not affecting your rank? It looks strange btw, I agree.

**Comment by RumbleMike** [comment]
This can happen, when it comes to number calculations the program is correct.
