### ISSUE TITLE
Dont know what to do

### ISSUE THREAD

**Issue by DaanvGG** [RumbleMike/ValorantStreamOverlay#155]
![image](https://user-images.githubusercontent.com/77209060/104106556-1af9bf80-52b7-11eb-99a2-dc1a286d7d25.png)

I get here after i download the file i onl have one file i can open called "ValorantStreamOverlay-main" what do i do from here i am so lost haha

**Comment by Mayonnaise1224** [comment]
same problem

**Comment by caoliheng** [comment]
Download the "ValorStreamOverlay.zip" file instead of the source code file (https://github.com/RumbleMike/ValorantStreamOverlay/releases).

**Comment by RumbleMike** [comment]
There is also a tutorial on the main page.
