### ISSUE TITLE
How can I update MANUALLY as I turned off auto update for 30 days.(Login error not fixing)

### ISSUE THREAD

**Issue by NoOne15j** [RumbleMike/ValorantStreamOverlay#159]
How can I update MANUALLY as I turned off auto update for 30 days.(Login error not fixing)

**Comment by RumbleMike** [comment]
i dont know what you mean by that, but https://github.com/RumbleMike/ValorantStreamOverlay/releases/tag/1.1.0.5 to fix login issues.

**Comment by NoOne15j** [comment]
thanks, it worked.
