### ISSUE TITLE
Iron 1 account showing 99 RP, 99 ELO, and no recent games

### ISSUE THREAD

**Issue by bgreal5** [RumbleMike/ValorantStreamOverlay#17]
I don't know if this is an edge case related to Iron 1, or something else, but RP and ELO are both at 99 and recent games are all blank.

My other account is in silver and is showing reasonable results (819 ELO, 19 RP, 3 recent games)

**Comment by DL108** [comment]
Hi there,

I have the same problem, initially same issue with the other project - ValorantRankedPoints, then I have tried this 1, and same issue;

![2020-12-29_21-50-14](https://user-images.githubusercontent.com/76733466/103337239-48f32e80-4a83-11eb-9c6d-020396922b10.jpg)

Please see above screen ( hope it attaches )
and this is after I played 15 games on the trot...

**Comment by JunctionNinja** [comment]
@DL108 You are hardstuck in Iron 1.
I have had the same issue.

Sadly, you're going to have to try too hard to get out (I'm in the same situation, don't worry).

**Comment by JunctionNinja** [comment]
Same goes for you @bgreal5, you are hardstuck too.

**Comment by bgreal5** [comment]
Truthfully, the iron 1 account isn’t actually my account, mainly wanted to use this to see how far into iron 1 hole my girlfriend’s account is. 

This utility shouldn’t really be falling down in the case that someone is iron 1, though, that’s a perfectly normal rank to be.

When I get some time I can try to make a PR to address this but I imagine it would be much quicker for the project owner to resolve this.

**Comment by Death2001** [comment]
wait.. I have this issue too..I keep playing with bronze 1 and iron 3's though...how I fix it??

**Comment by Arjun8525** [comment]
samke issue with me :(

**Comment by skittles9823** [comment]
I think the reason this issue exists is because it doesn't take into account the fact that iron 1 can have negative elo.

As far as I'm aware, iron 1 acts similar but opposite to radiant where you can continue to lose elo without deranking.

**Comment by bgreal5** [comment]
It doesn’t make sense why you don’t show the negative number then, to see how much progress you need to make. Why show 99 instead of the negative number?
