### ISSUE TITLE
Program stopped working // INVALID_HEADERS

### ISSUE THREAD

**Issue by tomsouris** [RumbleMike/ValorantStreamOverlay#176]
The program no longer works for me. 
I have tried to find out what the problem is:
It looks like there has been a change to the API for the following call ->
https://pd.{region}.a.pvp.net/mmr/v1/players/{UserID}/competitiveupdates?startIndex=0&endIndex=20

It returns "{\"httpStatus\":400,\"errorCode\":\"INVALID_HEADERS\",\"message\":\"Bad headers used for request\"}\n"

**Comment by RumbleMike** [comment]
Yes riot has changed how the headers function. This is gonna take awhile to figure out :(

**Comment by tomsouris** [comment]
I try to help u getting it working again

**Comment by RumbleMike** [comment]
Fix coming in the next few hours.
