### ISSUE TITLE
Wrong indicator

### ISSUE THREAD

**Issue by Xamir307** [RumbleMike/ValorantStreamOverlay#179]
Hello,
instead of Elo, it shows TRR is that correct ?
also RR instead of RP

did I do something wrong ?
![grafik](https://user-images.githubusercontent.com/78083674/105986342-185fde00-609d-11eb-8889-7b673be90e3b.png)

**Comment by HeyM1ke** [comment]
RR = Rank Rating, which is the official name by riot.
TRR = Total Rank Rating, which is all the points you have to your name.
