### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by tays9** [RumbleMike/ValorantStreamOverlay#18]
I downloaded .zip file....unpacked and did everything you said, then downloaded and instaled .net core 3.1...and when i try to run the app i says "To run the applicatin you must instal .Net core " what should i do? Thanks

**Comment by Spartanac885** [comment]
install .net core x86

**Comment by sunohonmy** [comment]
how long does it take to install the net core, cuz after i press yes, nothin happens???

**Comment by alexcarrilloar** [comment]
Less than 5 minutes. When you press 'yes' it should open the official site to download .net core, after that, run the net core .exe It's a simple installation wizard.
