### ISSUE TITLE
Microsoft .NET - Value cannot be null (Parameter 'o')

### ISSUE THREAD

**Issue by s3bbie** [RumbleMike/ValorantStreamOverlay#185]
Hi, I'm experiencing this issue whenever I try to open the Valorant Stream Overlay.
![image](https://user-images.githubusercontent.com/18750041/119254560-e3791900-bbae-11eb-84dd-cf2a87286c76.png)

Any idea what it means?

**Comment by Mofsuo** [comment]
Did you fix it ?

**Comment by Mofsuo** [comment]
Same problem for me...

**Comment by marshyyo** [comment]
any fix yet ?

**Comment by Mofsuo** [comment]
Nope

**Comment by ManWooDz** [comment]
Guys, I don't know what's happening, but today I run it after Valorant, and it's working without problem.
![image](https://user-images.githubusercontent.com/67360141/120105740-794f0e00-c184-11eb-9a9f-a0a9b09143b1.png)
