### ISSUE TITLE
Stats won't update.

### ISSUE THREAD

**Issue by JunctionNinja** [RumbleMike/ValorantStreamOverlay#2]
Been playing for the past like 3 hours and stats haven't updated at all.
![image](https://user-images.githubusercontent.com/62995181/103171446-3fc84e80-4844-11eb-8344-05fa16c31d02.png)

**Comment by JunctionNinja** [comment]
I've set it to the right region and what not. Right login and everything.
![image](https://user-images.githubusercontent.com/62995181/103171467-64242b00-4844-11eb-9063-17e32a652aa3.png)

**Comment by RumbleMike** [comment]
Hmm, well this is interesting go ahead and message me on Twitter or discord `RumbleMike#0001` let's get this resolved.

**Comment by RumbleMike** [comment]
Closing: After talking he has not gained any elo in 3 matches!
