### ISSUE TITLE
Datei Starten

### ISSUE THREAD

**Issue by Neverking471** [RumbleMike/ValorantStreamOverlay#20]
Ich habe den .net Core #68 heruntergeladen aber kann weiterhin die datei nicht ausführen was kann ich machen?

**Comment by BobbyESP** [comment]
I translated the message. The program gives you an error or just it gets auto closed??

**Comment by baseram** [comment]
bei versionen installieren dann geht es, bei mir ging die 64bit version nicht aber 32bit dafür

**Comment by kluedox** [comment]
musst die 32 bit version vom .net installieren

**Comment by Neverking471** [comment]
wo kann ich genau das .net instalieren, ich finde nicht das richtige. Hat jemand einen Link dazu?

**Comment by BobbyESP** [comment]
Install the x86 versionof .NET

**Comment by baseram** [comment]
kannst du doch auswählen auf der page, x86 steht für 32bit version
