### ISSUE TITLE
Please add Latin America regions

### ISSUE THREAD

**Issue by bryang8** [RumbleMike/ValorantStreamOverlay#23]
![6637F52A-41DC-4216-9101-D59A4AF4BE83](https://user-images.githubusercontent.com/14056641/103387408-34398980-4ac9-11eb-8ebd-6ff31c3ada70.jpeg)

**Comment by RumbleMike** [comment]
Use AP

**Comment by trollman877** [comment]
Disculpe la molestia, pero ¿Qué el AP ?

**Comment by RumbleMike** [comment]
Asia Pacific, but for LATAM you want to use NA
