### ISSUE TITLE
Overlay say "unrated"

### ISSUE THREAD

**Issue by MrAzgard** [RumbleMike/ValorantStreamOverlay#26]
Logged in fine, but the overlay says that i'm unrated with 0 rp and -300elo.
Not sure if its just a bug or not
![sgsgs](https://user-images.githubusercontent.com/76798393/103389756-ea9e7c80-4b64-11eb-9bcb-8aa92ad3f295.png)

**Comment by RumbleMike** [comment]
Check your set region

**Comment by Wowowow1234** [comment]
I got the same problem server region is NA which is correct, but I haven't played ranked in a week or so maybe it'll update after I play a ranked game?

**Comment by MrAzgard** [comment]
> Check your set region

It was set the the right region.

I just reopened the app, and it told me to update it to 1.0.0.1
And that fixed it
