### ISSUE TITLE
Unhandled exception has occured?

### ISSUE THREAD

**Issue by noshowpt** [RumbleMike/ValorantStreamOverlay#3]
Does someone know why is this happening? Yesterday it was working fine... Thanks!

![print1](https://user-images.githubusercontent.com/76660984/103177068-0527db80-486f-11eb-903b-16b052e3b550.PNG)

**Comment by KhabKwon** [comment]
I have the same issue it worked literally 30 minutes ago and now I get the same result as you

**Comment by Nekiior** [comment]
same

**Comment by fuckingrach** [comment]
same C:

**Comment by skittles9823** [comment]
Update to the new version, should fix the issue.

**Comment by Maetness** [comment]
same

**Comment by noshowpt** [comment]
> Update to the new version, should fix the issue.

new version fixes the problem indeed, thanks!
