### ISSUE TITLE
This is not exactly about the program idk

### ISSUE THREAD

**Issue by valvebj** [RumbleMike/ValorantStreamOverlay#36]
i created my acc with google so i dont really have a riot username, does somebody know how to enter or to figure out the username, when i enter in valorant official page doesnt say nothing about my username

**Comment by Justinsst** [comment]
I have the same issue :(

**Comment by Justinsst** [comment]
SOLUTION: You have to create a ticket with Riot to upgrade your account if you made it with social sign in. After you upgrade the account you'll now have a username and password and the program will work.
