### ISSUE TITLE
unreted elo and -300

### ISSUE THREAD

**Issue by buldose11** [RumbleMike/ValorantStreamOverlay#37]
<img width="283" alt="Captura" src="https://user-images.githubusercontent.com/76827081/103430961-f7d06100-4b8e-11eb-8fba-5b8ecae96000.PNG">

apparently opening my account appears this and shows nothing about my elo although I think it is because it has not added the region of latam so I can not determine my elo in another region

**Comment by RumbleMike** [comment]
LATAM uses NA
