### ISSUE TITLE
Region Problem

### ISSUE THREAD

**Issue by trollman877** [RumbleMike/ValorantStreamOverlay#39]
Excuse me but you can't add to the LAN region because he won't let me open another way to change it, I read one that said about the AP but I don't know what that is. Thanks for your time

**Comment by RumbleMike** [comment]
Have you tried the AP region?

**Comment by trollman877** [comment]
> ¿Has probado la región AP?

Yes I tried, but it has not served me, I tried with the 4 regions that appear to me that are: Asia Pacific, Korea, Europe and North America

**Comment by RumbleMike** [comment]
Hmm Message me on discord : https://discord.gg/ZJCQRWjKtR
