### ISSUE TITLE
Application not running then deleting

### ISSUE THREAD

**Issue by itsmvdc** [RumbleMike/ValorantStreamOverlay#42]
After downloading and unzipping, I ran the program and nothing happened. Program shows as running in 'Background Tasks' but does not respond, and on restart of PC the Application file is gone - not in Recycle Bin, seems to have permanently deleted...

**Comment by IZNOLY** [comment]
It's the anti-virus :d

**Comment by itsmvdc** [comment]
Is there any fix?

**Comment by RumbleMike** [comment]
Hmm typically windows scans it for around 10 seconds, try ending the task and running it again.

**Comment by itsmvdc** [comment]
Ending the task in Task Manager crashes my PC, I have to restart to close it...

**Comment by RumbleMike** [comment]
That makes no sense. lol

**Comment by RumbleMike** [comment]
Seems like a windows issue, or a possible anti-virus issue, the program can be run through virustotal and it shows nothing, very odd.

**Comment by itsmvdc** [comment]
Fixed. Bullguard was quarantining the file without alerting me. Thanks!
