### ISSUE TITLE
Why do I need to type in my password?

### ISSUE THREAD

**Issue by StephyWephy** [RumbleMike/ValorantStreamOverlay#43]
I really want to use this program but I can't help but stress a little about sharing my password..I just want a reason on why you guys need the password.

**Comment by RumbleMike** [comment]
Well, if you are scared to use it don't. No one is forcing you, otherwise, the code is public and you can see where your password is being stored and sent too. The password is sent to riot only and then stored on your computer.

**Comment by SharpBit** [comment]
@RumbleMike is the password hashed before it's sent to riot?
