### ISSUE TITLE
I can not open the overlay because it is a psd file 

### ISSUE THREAD

**Issue by Burniic** [RumbleMike/ValorantStreamOverlay#44]
I can't open the overlay because it is a psd file. Do I need another program for this? or can someone send me this overlay in a jpg file?

Thanks in advance

I apologize for an English as I don't know English and did all this with a translator.

**Comment by roljy** [comment]
The overlay is a .exe file. You can get it from the latest release by downloading the .zip (not the .psd) and unzipping it on your computer. The .psd file is just for customizing the appearance of the overlay.
![image](https://user-images.githubusercontent.com/62124462/103445137-b80c8680-4c2d-11eb-9504-de58180264d9.png)
