### ISSUE TITLE
Getting error "Login is incorrect" on the overlay

### ISSUE THREAD

**Issue by Maximillion195** [RumbleMike/ValorantStreamOverlay#48]
First off thanks for making this, looks really useful and will alleviate some pain by getting more info when winning / losing matches!

I have added my login details in the settings and set my region to Europe but am getting the error "Login is incorrect".

I tried logging into riot's web portal with the same details and it works fine but I have to do 2FA authentication as it sends a code to my email. Could this be the issue?

**Comment by halfurness** [comment]
I got this issue, I had changed my username since creating my account and when using my original username it worked!

**Comment by Maximillion195** [comment]
Thanks for the reply, I also had to change my username since creating my account but using my old one still doesn't work.

I tried doing the api call myself in case it gave a more useful error, but all I get is this 

`{
    "type": "auth",
    "error": "auth_failure",
    "country": "gbr"
}`

**Comment by Maximillion195** [comment]
Okay looks like I found the issue. I have a quote symbol in my password, looks like it was breaking the json request.

**Comment by TGCAras** [comment]
Same thing here. I was able to get it working in the 0.9.9.9 Version by escaping both the escape and the quote in the json file ("`\\\"`"). This does not seem to work any longer in the 1.0 release when prompted in the GUI.

**Comment by Luis-VI** [comment]
Hello, despite having uninstalled and installed the program I still get the message "Login is incorrect, please fix login in settings." And I already made sure that my username is well written, as well as my password. even reading the posts above I used my old username and it doesn't work. Is there any solution?

**Comment by RumbleMike** [comment]
Actually, i am going to look into this now, I never thought about this issue.

**Comment by HolidayLNX** [comment]
> Same thing here. I was able to get it working in the 0.9.9.9 Version by escaping both the escape and the quote in the json file ("`\\\"`"). This does not seem to work any longer in the 1.0 release when prompted in the GUI.

How do you do this?.. Think I have the same issue. Sorry I'm not familiar with coding.

**Comment by TGCAras** [comment]
> > Same thing here. I was able to get it working in the 0.9.9.9 Version by escaping both the escape and the quote in the json file ("`\\\"`"). This does not seem to work any longer in the 1.0 release when prompted in the GUI.
> 
> How do you do this?.. Think I have the same issue. Sorry I'm not familiar with coding.

When you are trying to pass text to a program, i.e. via a json file like in v0.9.9.9, you need some way of differentiation when it comes to special characters like `"` because this could either mean "I'm the end/beginning of some text" or "I'm actually just what I am, a `"`-Symbol".
To achieve this, there is another special character, the backslash `\`. This tells the program to ignore the special meaning of what ever character comes next and just interpret it as the raw symbol.
In theory "\"" is enough to Create a string/text that only contains the quote symbol but I assume that the string is parsed a second time further down the line causing the string to lose the information that the quote symbol is only meant as the symbol, not a string start/end. Therefore we pass "\\\"" which leaves a backslash and a quote symbol the first time it is parsed so the second time it is parsed, we still get the "\"" telling the program it still is just a quote symbol.

Hope this helps to roughly wrap your hand around what is happening.

**Comment by HolidayLNX** [comment]
> > > Same thing here. I was able to get it working in the 0.9.9.9 Version by escaping both the escape and the quote in the json file ("`\\\"`"). This does not seem to work any longer in the 1.0 release when prompted in the GUI.
> > 
> > 
> > How do you do this?.. Think I have the same issue. Sorry I'm not familiar with coding.
> 
> When you are trying to pass text to a program, i.e. via a json file like in v0.9.9.9, you need some way of differentiation when it comes to special characters like `"` because this could either mean "I'm the end/beginning of some text" or "I'm actually just what I am, a `"`-Symbol".
> To achieve this, there is another special character, the backslash `\`. This tells the program to ignore the special meaning of what ever character comes next and just interpret it as the raw symbol.
> In theory """ is enough to Create a string/text that only contains the quote symbol but I assume that the string is parsed a second time further down the line causing the string to lose the information that the quote symbol is only meant as the symbol, not a string start/end. Therefore we pass "\"" which leaves a backslash and a quote symbol the first time it is parsed so the second time it is parsed, we still get the """ telling the program it still is just a quote symbol.
> 
> Hope this helps to roughly wrap your hand around what is happening.

Thanks man.. I understand it now. I changed the password to a simpler one and now its working. 👍
