### ISSUE TITLE
Pressing tab in settings dialog focusses on cancel button and not next input field.

### ISSUE THREAD

**Issue by roljy** [RumbleMike/ValorantStreamOverlay#49]
Minor quality of life issue. Settings dialog would be easier to navigate if tabbing focussed on the next input field (eg. username --> password) instead of on the cancel button (which doesn't work anyways as of patch 1.0.0.0). Looking forward to more cool features in the coming updates!

**Comment by RumbleMike** [comment]
This will be fixed soon, just an error on my end :)
