### ISSUE TITLE
Too many requests for "rankInfo.json"

### ISSUE THREAD

**Issue by boomxch** [RumbleMike/ValorantStreamOverlay#5]
This issue may overlap with other issues.
In ``Program.cs``, it's trying to download a file in the Dropbox, but it is inaccessible due to excessive requests.
![image](https://user-images.githubusercontent.com/6965987/103178359-7a260000-48c5-11eb-82d4-c25d1cc8d0b9.png)
![ac](https://user-images.githubusercontent.com/6965987/103178394-cec97b00-48c5-11eb-86e7-ab9d8d970431.png)

**Comment by RumbleMike** [comment]
New Build is out that fixes the issue.
