### ISSUE TITLE
you must install .net core

### ISSUE THREAD

**Issue by rashoso** [RumbleMike/ValorantStreamOverlay#53]
i instaled it and reinstalled and nothing :/

**Comment by Stewartdestroyer** [comment]
is the same with me... first it said that i need to install it.. now that i have it... it does not say anything and it does not matter how many times i try it it is the same thing

**Comment by AfricanMunk69** [comment]
I had the same issue, when downloading the .net core download the x84 version not x86.

**Comment by tensins** [comment]
@rashoso  @Stewartdestroyer @AfricanMunk69 install -> program files/dotnet (or wherever you installed it) -> run the dotnet application and then run ValorantOverlay
