### ISSUE TITLE
Elo not showing 

### ISSUE THREAD

**Issue by shamit007** [RumbleMike/ValorantStreamOverlay#62]
my elo is stuck at 99 and both rp and elo is 99 / 99 @RumbleMike 
![Screenshot_107](https://user-images.githubusercontent.com/72201522/103459845-c6df6000-4d37-11eb-8a5d-28e87d30f1b1.png)

**Comment by shamit007** [comment]
@RumbleMike  plz reply

**Comment by skittles9823** [comment]
There are a good 3 - 4 issues about the exact same thing. Look at #17 for all the info you need instead of creating a new issue.
