### ISSUE TITLE
Don't Understand why the data is wrong for my account

### ISSUE THREAD

**Issue by HolidayLNX** [RumbleMike/ValorantStreamOverlay#66]
I don't think the overlay is showing the right info for my account. I won my last 2 matches and still its showing my RP as decreased. Compare the data in this Screenshot.. Can sm1 help me out?
![Capture](https://user-images.githubusercontent.com/76883571/103465480-d1aeea80-4d61-11eb-80fb-6b9b8c9ed7c1.PNG)

**Comment by BobbyESP** [comment]
Maybe what is showing good the info is the overlay but now the game. Listen, RP are YOUR stats compared to the rest of the people, so, Now you lost a little of your hability regarding the rest of the people. U understand me??

**Comment by HolidayLNX** [comment]
> Maybe what is showing good the info is the overlay but now the game. Listen, RP are YOUR stats compared to the rest of the people, so, Now you lost a little of your hability regarding the rest of the people. U understand me??

Not really.. do you mean that RP is not accurate and its just a number assumed considering all the players performance in that match?

**Comment by HolidayLNX** [comment]
Btw.. i got this on my other account too.. Why is it showing a negative RP for "Rating slightly increased" matches??????

**Comment by BobbyESP** [comment]
> Not really.. do you mean that RP is not accurate and its just a number assumed considering all the players performance in that match?

In the hole rank, i think

**Comment by BobbyESP** [comment]
> Btw.. i got this on my other account too.. Why is it showing a negative RP for "Rating slightly increased" matches??????

Oof. Interesting... @RumbleMike See this
