### ISSUE TITLE
All settings are reset after update to v1.1 with the auto-updater

### ISSUE THREAD

**Issue by very-lame-username** [RumbleMike/ValorantStreamOverlay#69]
I just updated to v1.1 via the update popup and all settings including username and password were reset.

~~Whilst I'm at it, is it possible for an oauth2 token to be used instead of your password being sent each time a request is made, still seems a bit insecure.~~ Just saw there is a dedicated issue for this.

**Comment by RumbleMike** [comment]
The setting reset is meant to happen, its security feature in a way
