### ISSUE TITLE
Application keeps asking me to install .NET Core

### ISSUE THREAD

**Issue by Maetness** [RumbleMike/ValorantStreamOverlay#7]
It's already installed. Even after multiple restarts and installing both the x64 and x86 versions of .NET Core 3.1 the Application does not launch.

**Comment by haithem2459** [comment]
asks the same thing for me as well

**Comment by RumbleMike** [comment]
Well, you only need the x86 version, but I am not sure on how to help at that is not a program issue instead it is a pc issue. Try to repair the framework.
