### ISSUE TITLE
One of my 2 accounts is not logging in on the program

### ISSUE THREAD

**Issue by HolidayLNX** [RumbleMike/ValorantStreamOverlay#71]
I have 2 accounts from which one of them is logged in perfectly but while i change the settings to log into my other account which is in the same region, i get this message:

![Capture](https://user-images.githubusercontent.com/76883571/103467684-87386880-4d77-11eb-8dea-525ac0f3f443.PNG)

And when i click okay I get this window :(

![ee](https://user-images.githubusercontent.com/76883571/103467703-b2bb5300-4d77-11eb-950f-10f8fec30ee2.PNG)

I have played comp on both accounts recently and i do not understand why there is an error like this. The only difference is 1 have complicated password with different characters and the other have a simple one with only letters and numbers which is the one logged in.. Does this have to do with anything?

**Comment by BobbyESP** [comment]
The other account contains special character? Like "/", "$"? More people are having that issue. Rumble will fix it in the next version. Sorry for the inconvenients.

**Comment by HolidayLNX** [comment]
> The other account contains special character? Like "/", "$"? More people are having that issue. Rumble will fix it in the next version. Sorry for the inconvenients.

Yep.. the password is a lot complicated.. I think I'm just gonna change the password for now. Not an inconvenience.. this program is a lot helpful. Im really thankful for this. :)

**Comment by HolidayLNX** [comment]
So... I changed my password to a simpler one.. and its working now!! :)
