### ISSUE TITLE
iron 1 rank

### ISSUE THREAD

**Issue by Susanoo10** [RumbleMike/ValorantStreamOverlay#77]
![image](https://user-images.githubusercontent.com/76895457/103472682-26d31680-4dcb-11eb-8146-1ede39f4ba3c.png)

hi im playing in iron and i win in several games. but why in the overlay didnt update my rank point ?

**Comment by gmagino** [comment]
having the same issue

**Comment by gmagino** [comment]
launching in admin doesnt fix. using x86 net core

**Comment by skittles9823** [comment]
Check issue #17 everything has been covered there.
