### ISSUE TITLE
Changing accounts in settings results in unrated 300 bug. 

### ISSUE THREAD

**Issue by TearLSC** [RumbleMike/ValorantStreamOverlay#78]
After entering and settings and changing username/password it tells program to restart which will apply the updated info. Bugged at unrated 300 for some reason. For clarification i entered my alt account info first and it appeared correctly but after changing username/password to my main, it bugged at unrated 300.

**Comment by mohnishkarri** [comment]
I have the same issue and the elo rating shows -300 and unrated even though I am iron 1 ranked.

**Comment by skittles9823** [comment]
if you haven't played ranked on the account in your last 20 games you'll have this issue. everything is covered in issue #17

**Comment by TearLSC** [comment]
oh ok thanks!
