### ISSUE TITLE
The overlay shows my rank as "Unrated"

### ISSUE THREAD

**Issue by LightyLightus** [RumbleMike/ValorantStreamOverlay#8]
The cmd method works fine but the Overlay method shows that my rank is Unrated. I downloaded the latest version 0.9.9 and tried but still the same.

https://user-images.githubusercontent.com/76685843/103207391-2ac2ec80-4924-11eb-96fc-d2c67b12b663.png

**Comment by BobbyESP** [comment]
First, check your config file. Make sure u have the login info good.

**Comment by RumbleMike** [comment]
Interesting seems that it is reading you as unrated.

**Comment by pajlek** [comment]
I just tried and it same result. I think it has to do with the fact that I don't have any ranked games lately, and all my matches from `"https://pd.{LogicHandler.region}.a.pvp.net/mmr/v1/players/{LogicHandler.UserID}/competitiveupdates"` 
have 
`game["CompetitiveMovement"] == "MOVEMENT_UNKNOWN"`

**Comment by RumbleMike** [comment]
This shouldn't break anything and will simply return a 0 if I remember if not it will be included in the final release 👍

**Comment by broccoli29586** [comment]
Im also having the same issues, not a clue why however...

**Comment by shakeabi** [comment]
Same issue, India region, any idea why??

**Comment by pajlek** [comment]
I resolved my issue when I started playing ranked games.. before that I didnt play ranked for 2 weeks.

**Comment by broccoli29586** [comment]
yeah i just did the same thing and it fixed it
