### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by Marwanamr9** [RumbleMike/ValorantStreamOverlay#81]
I downloaded and installed it and it still showing the same error that i need to download it

**Comment by Whanos** [comment]
Hey there. You probably didn't install the right .NET SDK.

Try https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.10-windows-x64-installer

**Comment by Marwanamr9** [comment]
> Hey there. You probably didn't install the right .NET SDK.
> 
> Try https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.10-windows-x86-installer

thanks man, i did installed the x64 at first yeah

**Comment by AdityaKane2001** [comment]
Minor question, why are we installing x86 for x64 systems also?

**Comment by Whanos** [comment]
It was made for x86. You require that SDK.
