### ISSUE TITLE
Elo not updating

### ISSUE THREAD

**Issue by TiPoutch** [RumbleMike/ValorantStreamOverlay#85]
Hello,

First of all, thanks for this great tool!

I have an issue with it: my elo does not change. it's stuck at 99 (yeah, Iron 1 player). And for the last 3 games, it's always showing 0 even if I won or lost.

The settings are ok, as it's able to find me and login correctly. Any idea what the issue could be?

Thanks!

**Comment by kellynelaine** [comment]
Hey, I had this issue on the first iteration of the program, and like OP, it has followed me here! 99 points, 99 ELO, Iron 1, and last 3 show 0 change even though they DEFINITELY impacted my rank.

**Comment by RumbleMike** [comment]
So odd seems everyone in iron 1 is stuck at 99

**Comment by mohnishkarri** [comment]
you are hard struck in iron 1. Check this out to clarify your doubts #17 .
