### ISSUE TITLE
Not sure if I should be demoted?

### ISSUE THREAD

**Issue by gdansantos** [RumbleMike/ValorantStreamOverlay#88]
I had 3 games.
1st game - promoted, RP was 20
2nd game - rating decreased RP was 0 

After the 2nd game, I was already expecting that I would get demoted if I lose.

But as you can see, in the 3rd game, we lost and I got Rating Decreased. But my RP and the app did not show any MINUS in RP it only said 0. May I know why?

Pictures for reference below. Thanks!

![valo](https://user-images.githubusercontent.com/21059405/103523345-0d12fb80-4ebf-11eb-881e-fa30602a2f0f.PNG)
![velo2](https://user-images.githubusercontent.com/21059405/103523350-0edcbf00-4ebf-11eb-9f2e-ecf233fa35d1.PNG)

**Comment by mohnishkarri** [comment]
the one reason can be that riot has increased the ability to have a longer stay at a rank and not get demoted easily. Or else the game has not yet been counted by riot. if it counts then it will be reflected in the app.

**Comment by RumbleMike** [comment]
i think there is a chance to get a free game when you are about to derank.
